// Ingredient reference data, transcribed verbatim from the lists provided
// by the project owner (not scraped from any third-party site):
//   1. POREClOGGING_LIST — a flat "known pore-clogging ingredient" list
//      (no numeric 0-5 grade given, just presence on the list).
//   2. FUNGAL_ACNE_INGREDIENTS — named ingredients with a malassezia-feeding
//      risk tier (low/medium/high).
//   3. KEYWORD_RISK_RULES — suffix/keyword heuristics for ingredients not
//      found verbatim (e.g. "... Palmitate" reads as high risk).

export const PORE_CLOGGING_LIST = [
  "(olive) oil", "(shea butter)", "(shea)", "(soja)", "a & d additive",
  "acetvlated lanolin", "acetylated lanolin", "acetylated lanolin alcohol",
  "acetylated wool fat", "acetylated wool wax", "active soil complex",
  "adansonia digitata l.", "agar", "ahnfeltia concinna",
  "ahnfeltia concinna extract", "ahnfeltiopsis concinna extract",
  "alaria esculenta", "alaria esculenta extract", "alga bladderwrack",
  "algae", "algae extract", "algea", "algin", "alginate", "alginic acid",
  "almond oil", "amyl cinnamal", "andiroba seed oil",
  "aphanothece sacrum polysaccharide", "apricot", "apricot kernel oil",
  "apricot oil", "arthrospira plantensis", "ascophyllum",
  "ascophyllum nodosum", "ascophyllum nodosum extract",
  "asparagopsis armata extract", "astrocaryum murumuru seed butter",
  "avocado", "avocado butter", "avocado oil", "babassu oil", "baobab",
  "baobab oil", "baoboab", "basic red", "beef tallow", "beeswax",
  "bismuth", "bismuth oxychloride", "black kelp", "bladderwack",
  "blue algae", "blue green algae", "borage oil", "brazil nut oil",
  "brown algae", "bryopsis africana", "buriti oil", "butyl stearate",
  "butyrospermum parkii butter", "butyrospermum", "butyrospermum parkii",
  "butyrospermum parkii (shea) butter",
  "butyrospermum parkii (shea) butter extract", "c13-14 isoparaffin",
  "cacao seed butter", "camelina oil", "canola oil",
  "capea biruncinata var. denuda sonder",
  "capea biruncinata var. elongata sonder", "capric acid",
  "carageenan gum", "carageenan moss", "carastay c", "carrageenan",
  "carrageenan moss", "carrot seed oil", "caulerpa filiformis",
  "caulerpa lentillifera extract", "cera alba", "cera bianca", "cera flava",
  "cera olea", "ceteareth 20", "ceteareth-20", "ceteareth-6 olivate",
  "cetearyl alcohol & ceteareth 20", "cetearyl alcohol + ceteareth 20",
  "cetrimonium bromide", "cetyl acetate",
  "chaetomorpha linum (aerea) cladophora radiosa", "cherry seed oil",
  "cheru seed oil", "chlamydomonas reinhardtii extract", "chlorophyceae",
  "chondrus crispus", "chondrus crispus (aka irish moss or carageenan moss)",
  "chondrus crispus powder", "chullu (wild apricot) seed oil",
  "cladophora cf. subsimplex", "cladosiphon okamuranus extract", "coal tar",
  "cocoa butter", "coconut", "coconut alkanes", "coconut butter",
  "coconut extract", "coconut fruit", "coconut nucifera extract",
  "coconut oil", "cocos nucifera", "cocos nucifera (coconut) fruit extract",
  "cocos nucifera (coconut) oil", "cocos nucifera oil",
  "cocos nucifera seed butter", "cocos nucifera (coconut/nuix de coco) oil",
  "codium fragile extract", "coenochloris signiensis extract",
  "colloidal sulfur", "corn", "corn oil", "cotton awws", "cotton awws oil",
  "cotton seed oil", "cottonseed oil", "cranberry seed oil", "creosote",
  "crithmum maritimum", "cupuacu butter", "cystoseira tamariscifolia extract",
  "d & c red", "d & c red # 17", "d & c red # 21", "d & c red # 3",
  "d & c red # 30", "d & c red # 36", "d & c red 17", "d & c red 19",
  "d & c red 21", "d & c red 27", "d & c red 3", "d & c red 30",
  "d & c red 33", "d & c red 36", "d & c red 4", "d & c red 40",
  "d & c red 6", "d & c red 7", "d & c red 9", "d-limonene",
  "d&c red #17", "d&c red #21", "d&c red #3", "d&c red #30", "d&c red #40",
  "date seed oil", "decyl oleate", "dhupa seed oil",
  "di (2 ethylhexyl) succinate", "dictyopteris membranacea",
  "dictyopteris polypodioides", "diisostearyl malate", "dilsea carnosa",
  "dilsea carnosa extract", "dioctyl malate", "dioctyl succinate",
  "disodium monooleamido", "disodium monooleamido peg 2- sulfosuccinate",
  "disodium monooleamido peg 2-sulfosuccinate", "dodecanoic acid", "dulse",
  "dunaliella salina extract", "durvillaea antarctica extract",

  "ecklonia", "ecklonia radiata", "enteromorpha compressa",
  "ethoxylated lanolin", "ethylhexyl palmitat", "eevening primrose oil",
  "flax oil", "flaxseed oil", "fucus vesiculosus", "glyceryl 3-diisostearate",
  "glyceryl stearate se", "glyceryl-3 diisostearate",
  "glycine soja (soybean) oil", "haslea ostrearia", "hexadecyl alcohol",
  "himanthalia elongate", "hydrolyzed wheat protein", "irish moss",
  "isoceteth-20", "isocetyl alcohol", "isocetyl stearate", "isodecyl oleate",
  "isononyl isononoanoate", "isopropyl isostearate", "isopropyl isosterate",
  "isopropyl lanolate", "isopropyl linolate", "isopropyl linoleate",
  "isopropyl myristate", "isopropyl neopentanoate", "isopropyl palmitate",
  "isostearate", "isostearic acid", "isostearyl", "isostearyl isostearate",
  "isostearyl neopentanoate", "jania rubens extract", "kapok oil",
  "kappaphycus", "kappaphycus alvarezii extract", "karanja oil", "karite",
  "kelp", "kousou ekisu", "kukui nut", "kukui nut oil", "kukui oil",
  "laminaria", "laminaria digitata", "laminaria digitata extract",
  "laminaria longicruris", "laminaria longicruris extract",
  "laminaria saccharina", "laminaria saccharina extract",
  "laminaria saccharina extract (laminaria saccharine)",
  "laminaria saccharine", "laneth 10", "lanolic acid", "lanolin",
  "lanolin alcohol", "lanolin oil", "laureth 12", "laureth 23",
  "laureth 4", "laureth 7", "laureth-23", "laureth-4", "lauric acid",
  "lauryl alcohol", "lauryl olivate", "lauryl sulfate", "linolate",
  "linseed", "linseed oil", "linum usitatissimum (linseed) seed oil",
  "liquor picis carbonis", "lithothamnium calcareum",
  "lithothamnium calcareum powder", "lola implexa", "lpc",
  "macadamia nut oil", "macroalgae", "macrocystis pyrifera (kelp) extract",
  "macrocystis pyrifera extract", "magnesium myristate", "mahua seed oil",
  "mangifera indica seed butter", "mango butter", "marine algae", "marula",
  "marula oil", "mastocarpus stellatus", "microcystis aeruginosa",
  "mineral oil", "mink oil", "monostearate", "moringa", "moringa oil",
  "moringa oleifera seed oil", "moss", "myreth 3 myristate",
  "myreth-3 myristate", "myristate", "myristic acid", "myristyl",
  "myristyl alcohol", "myristyl lactate", "myristyl myristate",
  "myristyl propionate", "myrtrimonium bromide", "nahor seed oil",
  "nasturtium officinale (watercress) flower/leaf extract", "neem oil",
  "neopentanoate", "norwegian kelp", "nymphaea alba flower extract",
  "octodidecyl stearoyl stearate", "octyl palmitate", "octyl stearate",
  "olea europaea fruit oil", "oleth-10", "oleth-20", "oleth-3",
  "oleth-3 phosphate", "oleth-5", "oleyl alcohol", "olive", "olive butter",
  "olive oil", "olive oil peg-7 esters",

  "padina pavonica", "padina pavonica extract", "palash oil",
  "palm kernel oil", "palm oil", "palm oil butter",
  "palmaria oalmarta extract (dulse)", "palmaria palmata extract",
  "palmaria palmate", "palmitic acid", "papaya seed oil", "parkii",
  "parrafin", "peach kernel oil", "peanut oil", "pecan oil",
  "peg 100 distearate", "PEG 150 Distearate", "PEG-150 Distearate",
  "peg 150 distearate", "peg 16 lanolin", "peg 2 sulfosuccinate",
  "peg 200 dilaurate", "peg 65", "peg 8 stearate", "peg-16 lanolin",
  "peg-200 dilaurate", "peg-8 stearate", "pelvetia canaliculata extract",
  "pentaerythrital", "pequot oil", "persea americana",
  "persea gratissima (avocado) oil", "petroleum", "pg caprylate/caprate",
  "pg dipelargonate", "pg monostearate", "phaeodactylum tricornutum extract",
  "phaeophyceae", "phytantriol", "phytessence wakame", "pilu oil",
  "pine nut oil", "pix carbonis", "plankton", "plankton extract",
  "polyglyceryl-2 isostearate", "polyglyceryl-3 diisostearate",
  "polyglyceryl-3 diiosostearate", "polyglyceryl-4 isostearate",
  "polyglyceryl-diisostearate", "polyquanterium-4",
  "polysiphonia elongata extract", "porphyra", "porphyra umbilicalis",
  "porphyridium", "porphyridium cruentum", "porphyridium cruentum extract",
  "potassium chloride", "potassium cocoate", "potassium salt",
  "ppg 10 cetyl ether", "ppg 12", "ppg 2 myristyl ether propionate",
  "ppg 2 myristyl propionate", "ppg 5 ceteth 10 phosphate",
  "ppg ceteth 10 phosphate", "ppg-2 myristyl", "ppg-2 myristyl propionate",
  "pracaxi oil", "propylene glycol monostearate", "prunus dulcis oil",
  "pumpkin seed oil", "pyrene coal tar pitch", "rapeseed oil",
  "ratanjyat oil", "red algae", "red palm oil", "retinyl palmitate",
  "rhodophyceae extract", "rhodophyta", "ricebran oil", "rice bran oil",
  "rockweed", "sal seed oil", "sandalwood seed oil", "sapote oil",
  "sargassum", "sargassum filipendula extract", "sargassum fillpendula extract",
  "sargassum fusiforme extract", "sclerocarya birrea",
  "sclerocarya birrea seed oil", "sea fern", "sea grass", "sea mayweed",
  "sea whip", "sea whip extract", "seaweed", "sesame", "sesame oil",
  "sesame seed", "sesamum indicum", "shark liver oil", "shark squalene",
  "shea", "shea butter", "shea nut oil", "sheep alcohol",
  "simmondsia chinensis seed wax", "sles", "sls", "sodium alginate",
  "sodium carbomer", "sodium laurel sulfate", "sodium laureth sulfate",
  "sodium lauryl sulfate", "soil minerals", "soja", "solulan 16",
  "sorbitan laurate", "sova", "soy", "soy oil", "soy protein", "soybean",
  "soybean oil", "sphacelaria", "spiraea ulmaria (meadowsweet) flower extract",
  "spirulina", "squalene", "starch", "stealkonium chloride", "steareth 10",
  "steareth 2", "steareth 20", "steareth-10", "stearic acid TEA",
  "stearyl heptanoate", "sulfated castor oil", "sulfosuccinate",
  "sulphated castor oil", "sunflower butter", "sweet almond butter",
  "sweet almond oil", "talc", "talcum", "tallow", "tamanu oil",
  "TEA stearate", "TEA-Stearate", "tetradecyl myristate", "theobroma butter",
  "theobroma cocoa seed butter", "theobroma oil", "tribehenin",
  "triethanolamine", "triticum aestivum", "triticum vulgare", "tucuma butter",
  "turkey red oil", "ulva fasciata", "ulva lactuca", "ulva rhacodes",
  "undaria", "undaria pinnatifida", "vegetable gelatin",
  "vitamin a palmitate", "vitamin e oil", "vitellaria paradoxa", "wakame",
  "water soluble sulfur", "wheat", "wheat germ glyceride", "wheat germ oil",
  "wool alcohol", "wool fat", "xanthophyta", "xylene", "zea mays",
];

export const FUNGAL_ACNE_INGREDIENTS = [
  // Fatty acids
  { name: "Lauric Acid", risk: "high" },
  { name: "Myristic Acid", risk: "high" },
  { name: "Palmitic Acid", risk: "high" },
  { name: "Stearic Acid", risk: "high" },
  { name: "Oleic Acid", risk: "high" },
  { name: "Linoleic Acid", risk: "high" },
  { name: "Linolenic Acid", risk: "high" },
  { name: "Arachidic Acid", risk: "high" },
  { name: "Behenic Acid", risk: "high" },
  { name: "Lignoceric Acid", risk: "high" },
  { name: "Pentadecanoic Acid", risk: "high" },
  { name: "Margaric Acid", risk: "high" },
  { name: "Undecylenic Acid", risk: "medium" },
  { name: "Tridecylic Acid", risk: "medium" },
  // Esters
  { name: "Isopropyl Myristate", risk: "high" },
  { name: "Isopropyl Palmitate", risk: "high" },
  { name: "Isopropyl Isostearate", risk: "high" },
  { name: "Ethylhexyl Palmitate", risk: "high" },
  { name: "Ethylhexyl Stearate", risk: "high" },
  { name: "Octyl Palmitate", risk: "high" },
  { name: "Decyl Oleate", risk: "high" },
  { name: "Cetyl Palmitate", risk: "high" },
  { name: "Glyceryl Stearate", risk: "high" },
  { name: "PEG-100 Stearate", risk: "high" },
  { name: "Sorbitan Oleate", risk: "high" },
  { name: "Sorbitan Stearate", risk: "high" },
  { name: "Sorbitan Isostearate", risk: "high" },
  { name: "Polyglyceryl-3 Diisostearate", risk: "high" },
  { name: "Diisostearyl Malate", risk: "high" },
  { name: "Pentaerythrityl Tetraisostearate", risk: "high" },
  { name: "Glycol Stearate", risk: "medium" },
  { name: "PEG-40 Hydrogenated Castor Oil", risk: "medium" },
  { name: "PEG-7 Glyceryl Cocoate", risk: "medium" },
  { name: "Triethylhexanoin", risk: "medium" },
  { name: "Polyglyceryl-2 Dipolyhydroxystearate", risk: "medium" },
  // Polysorbates
  { name: "Polysorbate 20", risk: "high" },
  { name: "Polysorbate 40", risk: "high" },
  { name: "Polysorbate 60", risk: "high" },
  { name: "Polysorbate 80", risk: "high" },
  // Oils
  { name: "Coconut Oil", risk: "high" },
  { name: "Olive Oil", risk: "high" },
  { name: "Avocado Oil", risk: "high" },
  { name: "Soybean Oil", risk: "high" },
  { name: "Wheat Germ Oil", risk: "high" },
  { name: "Macadamia Oil", risk: "high" },
  { name: "Sesame Oil", risk: "high" },
  { name: "Argan Oil", risk: "medium" },
  { name: "Jojoba Oil", risk: "medium" },
  { name: "Rosehip Oil", risk: "medium" },
  { name: "Sunflower Oil", risk: "medium" },
  { name: "Grapeseed Oil", risk: "medium" },
  { name: "Safflower Oil", risk: "medium" },
  { name: "Marula Oil", risk: "medium" },
  { name: "Evening Primrose Oil", risk: "medium" },
  { name: "Rice Bran Oil", risk: "medium" },
  { name: "Camellia Seed Oil", risk: "medium" },
  { name: "Castor Oil", risk: "low" },
  // Butters & waxes
  { name: "Shea Butter", risk: "high" },
  { name: "Cocoa Butter", risk: "high" },
  { name: "Mango Butter", risk: "high" },
  { name: "Kokum Butter", risk: "high" },
  { name: "Cupuaçu Butter", risk: "high" },
  { name: "Beeswax", risk: "medium" },
  // Fatty alcohols
  { name: "Cetyl Alcohol", risk: "medium" },
  { name: "Cetearyl Alcohol", risk: "medium" },
  { name: "Stearyl Alcohol", risk: "medium" },
  { name: "Behenyl Alcohol", risk: "medium" },
  { name: "Lauryl Alcohol", risk: "medium" },
  { name: "Myristyl Alcohol", risk: "medium" },
  { name: "Oleyl Alcohol", risk: "medium" },
  // Lanolin derivatives
  { name: "Lanolin", risk: "high" },
  { name: "Lanolin Alcohol", risk: "high" },
  { name: "Acetylated Lanolin", risk: "high" },
  // Ferments & algae (evidence mixed)
  { name: "Galactomyces Ferment Filtrate", risk: "low" },
  { name: "Saccharomyces Ferment", risk: "low" },
  { name: "Bifida Ferment Lysate", risk: "low" },
  { name: "Lactobacillus Ferment", risk: "low" },
  { name: "Yeast Extract", risk: "low" },
  { name: "Algae Extract", risk: "low" },
  { name: "Seaweed Extract", risk: "low" },
  { name: "Kelp Extract", risk: "low" },
];

// Ingredients confirmed fungal-acne safe with a none/low pore-clogging
// risk, transcribed verbatim from the reference table provided by the
// project owner. "none" / "low" map to ingredients.comedogenic_rating
// (0 / 1) — this is a numeric-graded source, unlike PORE_CLOGGING_LIST.
// Ingredients here are NOT added to fungal_acne_risk or pore_clogging:
// those columns only ever record a *flagged* risk, and absence of a flag
// already means "not known to be a trigger" under this schema.
export const FUNGAL_ACNE_SAFE_INGREDIENTS = [
  { name: "Water", category: "Solvent", comedogenicRisk: "none", aliases: ["Aqua", "Eau"] },
  { name: "Aloe Vera Juice", category: "Humectant", comedogenicRisk: "none" },
  { name: "Glycerin", category: "Humectant", comedogenicRisk: "none" },
  { name: "Butylene Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Propylene Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Pentylene Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Hexylene Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Dipropylene Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Caprylyl Glycol", category: "Humectant", comedogenicRisk: "none" },
  { name: "1,2-Hexanediol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Sodium PCA", category: "Humectant", comedogenicRisk: "none" },
  { name: "Betaine", category: "Humectant", comedogenicRisk: "none" },
  { name: "Trehalose", category: "Humectant", comedogenicRisk: "none" },
  { name: "Erythritol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Xylitol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Hyaluronic Acid", category: "Humectant", comedogenicRisk: "none" },
  { name: "Sodium Hyaluronate", category: "Humectant", comedogenicRisk: "none" },
  { name: "Hydrolyzed Hyaluronic Acid", category: "Humectant", comedogenicRisk: "none" },
  { name: "Polyglutamic Acid", category: "Humectant", comedogenicRisk: "none" },
  { name: "Urea", category: "Humectant", comedogenicRisk: "none" },
  { name: "Saccharide Isomerate", category: "Humectant", comedogenicRisk: "none" },
  { name: "Panthenol", category: "Barrier Support", comedogenicRisk: "none" },
  { name: "Allantoin", category: "Soothing", comedogenicRisk: "none" },
  { name: "Madecassoside", category: "Soothing", comedogenicRisk: "none" },
  { name: "Asiaticoside", category: "Soothing", comedogenicRisk: "none" },
  { name: "Centella Asiatica Extract", category: "Soothing", comedogenicRisk: "none" },
  { name: "Green Tea Extract", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Licorice Root Extract", category: "Soothing", comedogenicRisk: "none" },
  { name: "Oat Extract", category: "Soothing", comedogenicRisk: "none" },
  { name: "Bisabolol", category: "Soothing", comedogenicRisk: "none" },
  { name: "Ectoin", category: "Barrier Support", comedogenicRisk: "none" },
  { name: "Beta-Glucan", category: "Barrier Support", comedogenicRisk: "none" },
  { name: "Dimethicone", category: "Silicone", comedogenicRisk: "low" },
  { name: "Cyclopentasiloxane", category: "Silicone", comedogenicRisk: "none" },
  { name: "Cyclohexasiloxane", category: "Silicone", comedogenicRisk: "none" },
  { name: "Dimethiconol", category: "Silicone", comedogenicRisk: "none" },
  { name: "Phenyl Trimethicone", category: "Silicone", comedogenicRisk: "low" },
  { name: "Polysilicone-11", category: "Silicone", comedogenicRisk: "none" },
  { name: "Amodimethicone", category: "Silicone", comedogenicRisk: "none" },
  { name: "Trimethylsiloxysilicate", category: "Silicone", comedogenicRisk: "none" },
  { name: "Salicylic Acid", category: "Active", comedogenicRisk: "none" },
  { name: "Azelaic Acid", category: "Active", comedogenicRisk: "none" },
  { name: "Sulfur", category: "Active", comedogenicRisk: "none" },
  { name: "Zinc PCA", category: "Active", comedogenicRisk: "none" },
  { name: "Zinc Gluconate", category: "Active", comedogenicRisk: "none" },
  { name: "Niacinamide", category: "Active", comedogenicRisk: "none" },
  { name: "Piroctone Olamine", category: "Active", comedogenicRisk: "none" },
  { name: "Ascorbic Acid", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Sodium Ascorbyl Phosphate", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Magnesium Ascorbyl Phosphate", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Ascorbyl Glucoside", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Ferulic Acid", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Resveratrol", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "EGCG", category: "Antioxidant", comedogenicRisk: "none" },
  { name: "Copper Peptides", category: "Peptide", comedogenicRisk: "none" },
  { name: "Acetyl Hexapeptide-8", category: "Peptide", comedogenicRisk: "none" },
  { name: "Palmitoyl Tripeptide-1", category: "Peptide", comedogenicRisk: "low" },
  { name: "Palmitoyl Tetrapeptide-7", category: "Peptide", comedogenicRisk: "low" },
  { name: "Carbomer", category: "Thickener", comedogenicRisk: "none" },
  { name: "Acrylates Copolymer", category: "Thickener", comedogenicRisk: "none" },
  { name: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", category: "Thickener", comedogenicRisk: "none" },
  { name: "Hydroxyethylcellulose", category: "Thickener", comedogenicRisk: "none" },
  { name: "Xanthan Gum", category: "Thickener", comedogenicRisk: "none" },
  { name: "Cellulose Gum", category: "Thickener", comedogenicRisk: "none" },
  { name: "Sodium Polyacrylate", category: "Thickener", comedogenicRisk: "none" },
  { name: "Polyquaternium-4", category: "Polymer", comedogenicRisk: "none" },
  { name: "Polyquaternium-7", category: "Polymer", comedogenicRisk: "none" },
  { name: "Polyquaternium-10", category: "Polymer", comedogenicRisk: "none" },
  { name: "Ethoxydiglycol", category: "Solvent", comedogenicRisk: "none" },
  { name: "Isododecane", category: "Solvent", comedogenicRisk: "none" },
  { name: "Isohexadecane", category: "Solvent", comedogenicRisk: "none" },
  { name: "C13-14 Isoparaffin", category: "Solvent", comedogenicRisk: "none" },
  { name: "Propanediol", category: "Humectant", comedogenicRisk: "none" },
  { name: "Silica", category: "Powder", comedogenicRisk: "none" },
  { name: "Kaolin", category: "Clay", comedogenicRisk: "none" },
  { name: "Bentonite", category: "Clay", comedogenicRisk: "none" },
  { name: "Titanium Dioxide", category: "Mineral", comedogenicRisk: "low" },
  { name: "Zinc Oxide", category: "Mineral", comedogenicRisk: "low" },
  { name: "Mica", category: "Mineral", comedogenicRisk: "none" },
  { name: "Cornstarch", category: "Powder", comedogenicRisk: "low" },
  { name: "Phenoxyethanol", category: "Preservative", comedogenicRisk: "none" },
  { name: "Ethylhexylglycerin", category: "Preservative", comedogenicRisk: "none" },
  { name: "Potassium Sorbate", category: "Preservative", comedogenicRisk: "none" },
  { name: "Sodium Benzoate", category: "Preservative", comedogenicRisk: "none" },
  { name: "Benzyl Alcohol", category: "Preservative", comedogenicRisk: "none" },
  { name: "Chlorphenesin", category: "Preservative", comedogenicRisk: "none" },
  { name: "Caprylhydroxamic Acid", category: "Preservative", comedogenicRisk: "none" },
  { name: "Squalane", category: "Emollient", comedogenicRisk: "low" },
  { name: "Mineral Oil", category: "Emollient", comedogenicRisk: "low" },
  { name: "Petrolatum", category: "Occlusive", comedogenicRisk: "low" },
  { name: "Hydrogenated Polyisobutene", category: "Emollient", comedogenicRisk: "low" },
];

export const KEYWORD_RISK_RULES = [
  { keyword: "Palmitate", risk: "high" },
  { keyword: "Stearate", risk: "high" },
  { keyword: "Oleate", risk: "high" },
  { keyword: "Isostearate", risk: "high" },
  { keyword: "Myristate", risk: "high" },
  { keyword: "Polysorbate", risk: "high" },
  { keyword: "Seed Oil", risk: "medium", notes: "ranges medium-high depending on the specific oil" },
  { keyword: "Butter", risk: "high" },
  { keyword: "Lanolin", risk: "high" },
  { keyword: "Cetyl/Cetearyl/Stearyl Alcohol", risk: "medium" },
];
